language: minimal

services:
  - docker

jobs:
  include:
    - stage: "Test JS/TS"
      language: node_js
      node_js: "18"
      install:
        - npm install
      script:
        - npm test

    - stage: "Test Elixir"
      language: elixir
      elixir: '1.14'
      otp_release: '25.0'
      install:
        - mix deps.get
      script:
        - mix test

    - stage: "Build Docker"
      script:
        - docker build -t umarshk7/gotham_time_manager:latest .
