language: elixir

elixir: '1.14'
otp_release: '25.0'

services:
  - docker

jobs:
  include:
    - stage: "Test Elixir"
      install:
        - mix local.hex --force
        - mix local.rebar --force
        - mix deps.get
      script:
        - mix test

    - stage: "Build Docker"
      script:
        - docker build -t umarshk7/gotham_time_manager:latest .
